
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '33D495BAD2919B4FD842EA0F8A6F56F7'
    
_lr_action_items = {'SUPERINDEX':([2,5,16,18,19,],[10,-13,21,-11,-12,]),'RPAREN':([1,2,3,5,9,14,15,16,17,18,19,22,23,],[-3,-6,-5,-13,-4,19,-7,-8,-2,-11,-12,-9,-10,]),'DIVIDE':([1,2,3,4,5,9,13,14,15,16,17,18,19,22,23,],[-3,-6,-5,12,-13,-4,12,12,-7,-8,-2,-11,-12,-9,-10,]),'LBRACKET':([0,1,2,3,5,6,8,9,10,11,12,15,16,17,18,19,20,21,22,23,],[6,6,-6,-5,-13,6,6,-4,6,6,6,-7,-8,6,-11,-12,6,6,-9,-10,]),'SUBINDEX':([2,5,15,18,19,],[11,-13,20,-11,-12,]),'LPAREN':([0,1,2,3,5,6,8,9,10,11,12,15,16,17,18,19,20,21,22,23,],[8,8,-6,-5,-13,8,8,-4,8,8,8,-7,-8,8,-11,-12,8,8,-9,-10,]),'RBRACKET':([1,2,3,5,9,13,15,16,17,18,19,22,23,],[-3,-6,-5,-13,-4,18,-7,-8,-2,-11,-12,-9,-10,]),'ID':([0,1,2,3,5,6,8,9,10,11,12,15,16,17,18,19,20,21,22,23,],[5,5,-6,-5,-13,5,5,-4,5,5,5,-7,-8,5,-11,-12,5,5,-9,-10,]),'$end':([1,2,3,4,5,7,9,15,16,17,18,19,22,23,],[-3,-6,-5,-1,-13,0,-4,-7,-8,-2,-11,-12,-9,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'A':([0,6,8,12,],[1,1,1,17,]),'S':([0,],[7,]),'B':([0,1,6,8,12,17,],[3,9,3,3,3,9,]),'E':([0,6,8,],[4,13,14,]),'C':([0,1,6,8,10,11,12,17,20,21,],[2,2,2,2,15,16,2,2,22,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> E','S',1,'p_expression_init','tp.py',60),
  ('E -> E DIVIDE A','E',3,'p_expression_E1','tp.py',64),
  ('E -> A','E',1,'p_expression_E2','tp.py',68),
  ('A -> A B','A',2,'p_expression_A1','tp.py',72),
  ('A -> B','A',1,'p_expression_A2','tp.py',75),
  ('B -> C','B',1,'p_expression_B1','tp.py',80),
  ('B -> C SUPERINDEX C','B',3,'p_expressionB2','tp.py',83),
  ('B -> C SUBINDEX C','B',3,'p_expressionB3','tp.py',86),
  ('B -> C SUPERINDEX C SUBINDEX C','B',5,'p_expressionB4','tp.py',89),
  ('B -> C SUBINDEX C SUPERINDEX C','B',5,'p_expressionB5','tp.py',92),
  ('C -> LBRACKET E RBRACKET','C',3,'p_expression_C1','tp.py',96),
  ('C -> LPAREN E RPAREN','C',3,'p_expression_C2','tp.py',100),
  ('C -> ID','C',1,'p_expression_C3','tp.py',106),
]
